const { Router } = require('express')
const pool = require('../db/pool')
const { parseId, serverError } = require('../utils/http')
const { dispatchWebhook } = require('../services/webhookService')
const router = Router()
const slugify = value => String(value || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 50) || `workspace-${Date.now()}`

async function access(workspaceId, userId) {
  const { rows } = await pool.query('SELECT w.id,w.owner_id AS "ownerId",w.name,w.slug,w.branding,wm.role FROM workspaces w JOIN workspace_members wm ON wm.workspace_id=w.id WHERE w.id=$1 AND wm.user_id=$2', [workspaceId, userId])
  return rows[0] || null
}

router.get('/', async (req, res) => { try { const { rows } = await pool.query('SELECT w.id,w.name,w.slug,w.branding,wm.role FROM workspaces w JOIN workspace_members wm ON wm.workspace_id=w.id WHERE wm.user_id=$1 ORDER BY w.criado_em DESC', [req.user.id]); res.json({ workspaces: rows }) } catch (err) { serverError(res, err) } })
router.post('/', async (req, res) => {
  const client = await pool.connect()
  try { const name = req.body?.name?.trim(); if (!name) return res.status(400).json({ erro: 'Informe o nome do espaço.' }); await client.query('BEGIN'); const { rows } = await client.query('INSERT INTO workspaces (owner_id,name,slug) VALUES ($1,$2,$3) RETURNING id,name,slug', [req.user.id, name, `${slugify(name)}-${Math.random().toString(36).slice(2, 6)}`]); await client.query('INSERT INTO workspace_members (workspace_id,user_id,role) VALUES ($1,$2,$3)', [rows[0].id, req.user.id, 'owner']); await client.query('COMMIT'); res.status(201).json({ workspace: rows[0] }) } catch (err) { await client.query('ROLLBACK').catch(() => {}); serverError(res, err) } finally { client.release() }
})
router.patch('/:id/branding', async (req, res) => { try { const id = parseId(req.params.id); const workspace = await access(id, req.user.id); if (!workspace || !['owner', 'admin'].includes(workspace.role)) return res.status(403).json({ erro: 'Sem permissão para editar a marca.' }); const branding = { name: String(req.body?.name || '').trim().slice(0, 120), logoUrl: String(req.body?.logoUrl || '').trim().slice(0, 500), primaryColor: /^#[0-9a-f]{6}$/i.test(req.body?.primaryColor || '') ? req.body.primaryColor : '#d9ad5b' }; await pool.query('UPDATE workspaces SET branding=$1 WHERE id=$2', [JSON.stringify(branding), id]); res.json({ branding }) } catch (err) { serverError(res, err) } })
router.get('/:id/members', async (req, res) => { try { const id = parseId(req.params.id); const workspace = await access(id, req.user.id); if (!workspace) return res.status(403).json({ erro: 'Sem acesso a este espaço.' }); const { rows } = await pool.query('SELECT u.id,u.email,u.full_name AS "fullName",wm.role,wm.criado_em AS "joinedAt" FROM workspace_members wm JOIN users u ON u.id=wm.user_id WHERE wm.workspace_id=$1 ORDER BY wm.criado_em ASC', [id]); res.json({ members: rows }) } catch (err) { serverError(res, err) } })
router.post('/:id/members', async (req, res) => { try { const id = parseId(req.params.id); const workspace = await access(id, req.user.id); if (!workspace || !['owner', 'admin'].includes(workspace.role)) return res.status(403).json({ erro: 'Sem permissão para convidar membros.' }); const email = req.body?.email?.trim().toLowerCase(); const role = ['admin', 'editor', 'reviewer'].includes(req.body?.role) ? req.body.role : 'editor'; const { rows: users } = await pool.query('SELECT id FROM users WHERE LOWER(email)=LOWER($1)', [email]); if (!users.length) return res.status(404).json({ erro: 'Usuário não encontrado. Ele precisa criar uma conta antes do convite.' }); await pool.query('INSERT INTO workspace_members (workspace_id,user_id,role) VALUES ($1,$2,$3) ON CONFLICT (workspace_id,user_id) DO UPDATE SET role=EXCLUDED.role', [id, users[0].id, role]); res.status(201).json({ ok: true }) } catch (err) { serverError(res, err) } })
router.get('/:id/approvals', async (req, res) => { try { const id = parseId(req.params.id); if (!await access(id, req.user.id)) return res.status(403).json({ erro: 'Sem acesso a este espaço.' }); const { rows } = await pool.query(`SELECT ar.id,ar.post_id AS "postId",ar.status,ar.feedback,ar.criado_em AS "createdAt",p.text,p.scheduled_at AS "scheduledAt" FROM approval_requests ar JOIN posts p ON p.id=ar.post_id WHERE ar.workspace_id=$1 ORDER BY ar.criado_em DESC`, [id]); res.json({ approvals: rows }) } catch (err) { serverError(res, err) } })
router.post('/:id/approvals', async (req, res) => { try { const id = parseId(req.params.id); const workspace = await access(id, req.user.id); const postId = parseId(req.body?.postId); if (!workspace || !postId) return res.status(400).json({ erro: 'Espaço ou publicação inválidos.' }); const { rows: posts } = await pool.query('SELECT id FROM posts WHERE id=$1 AND user_id=$2', [postId, req.user.id]); if (!posts.length) return res.status(404).json({ erro: 'Publicação não encontrada.' }); const { rows } = await pool.query('INSERT INTO approval_requests (workspace_id,post_id,requested_by) VALUES ($1,$2,$3) RETURNING id,status', [id, postId, req.user.id]); res.status(201).json({ approval: rows[0] }) } catch (err) { serverError(res, err) } })
router.patch('/approvals/:approvalId', async (req, res) => { try { const approvalId = parseId(req.params.approvalId); const status = ['approved', 'rejected', 'pending'].includes(req.body?.status) ? req.body.status : null; if (!status) return res.status(400).json({ erro: 'Status inválido.' }); const { rows } = await pool.query('SELECT workspace_id,post_id,requested_by FROM approval_requests WHERE id=$1', [approvalId]); if (!rows.length || !await access(rows[0].workspace_id, req.user.id)) return res.status(403).json({ erro: 'Sem acesso a esta aprovação.' }); await pool.query('UPDATE approval_requests SET status=$1,feedback=$2,reviewed_by=$3,revisado_em=NOW() WHERE id=$4', [status, req.body?.feedback?.trim() || null, req.user.id, approvalId]); dispatchWebhook('approval_updated', { approvalId, postId: rows[0].post_id, status }, rows[0].requested_by).catch(() => {}); res.status(204).send() } catch (err) { serverError(res, err) } })

module.exports = router
