import { useCallback, useEffect, useState } from 'react'
import { apiFetch } from '../lib/api.js'
import { useToast } from '../components/ui/toast.jsx'

export function AutomationsPage() {
  const [webhooks, setWebhooks] = useState([])
  const [apiKeys, setApiKeys] = useState([])
  const [form, setForm] = useState({ name: '', url: '' })
  const notify = useToast()
  const load = useCallback(() => Promise.all([apiFetch('/api/webhooks'), apiFetch('/api/api-keys')]).then(([webhookData, keyData]) => { setWebhooks(webhookData.webhooks || []); setApiKeys(keyData.apiKeys || []) }), [])
  useEffect(() => { load().catch(error => notify(error.message, 'error')) }, [load, notify])
  async function save(event) { event.preventDefault(); try { const data = await apiFetch('/api/webhooks', { method: 'POST', body: JSON.stringify({ name: form.name, url: form.url, selectedEvents: ['post_published', 'approval_updated'] }) }); setForm({ name: '', url: '' }); await load(); window.alert(`Webhook criado. Guarde este segredo agora: ${data.secret}`); notify('Webhook criado.') } catch (error) { notify(error.message, 'error') } }
  async function toggle(webhook) { try { await apiFetch(`/api/webhooks/${webhook.id}`, { method: 'PATCH', body: JSON.stringify({ active: !webhook.active }) }); await load() } catch (error) { notify(error.message, 'error') } }
  async function remove(id) { if (!window.confirm('Excluir este webhook?')) return; try { await apiFetch(`/api/webhooks/${id}`, { method: 'DELETE' }); setWebhooks(current => current.filter(item => item.id !== id)); notify('Webhook removido.') } catch (error) { notify(error.message, 'error') } }
  async function createKey() { const name = window.prompt('Nome da API key'); if (!name) return; try { const data = await apiFetch('/api/api-keys', { method: 'POST', body: JSON.stringify({ name }) }); await load(); window.alert(`API key criada. Guarde-a agora: ${data.key}`); notify('API key criada.') } catch (error) { notify(error.message, 'error') } }
  async function revokeKey(id) { if (!window.confirm('Revogar esta API key?')) return; try { await apiFetch(`/api/api-keys/${id}`, { method: 'DELETE' }); setApiKeys(current => current.filter(item => item.id !== id)); notify('API key revogada.') } catch (error) { notify(error.message, 'error') } }
  return <section className="page-view"><header className="panel-heading"><div><p className="eyebrow">INTEGRAÇÕES AVANÇADAS</p><h2>Automações e webhooks</h2><p className="panel-subtitle">Conecte o MeuEcooMidia a CRM, planilhas, atendimento ou outros sistemas.</p></div></header><section className="panel"><form className="grid gap-3 md:grid-cols-[1fr_2fr_auto]" onSubmit={save}><input className="rounded-lg border border-subtle bg-app px-3 py-2 text-sm text-zinc-100" value={form.name} onChange={event => setForm(current => ({ ...current, name: event.target.value }))} placeholder="Nome da integração" required/><input className="rounded-lg border border-subtle bg-app px-3 py-2 text-sm text-zinc-100" type="url" value={form.url} onChange={event => setForm(current => ({ ...current, url: event.target.value }))} placeholder="https://seu-sistema.com/webhook" required/><button className="action-button">Adicionar webhook</button></form><p className="mt-3 text-xs text-zinc-500">Eventos disponíveis: publicação concluída e atualização de aprovação. Cada webhook recebe assinatura HMAC SHA-256.</p><div className="mt-5 space-y-2">{webhooks.length ? webhooks.map(webhook => <article className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-subtle bg-app p-3" key={webhook.id}><div><strong>{webhook.name}</strong><small className="ml-2 text-zinc-500">{webhook.url}</small><p className="mt-1 text-xs text-zinc-500">Último status: {webhook.lastStatus || 'ainda não acionado'}{webhook.lastError ? ` · ${webhook.lastError}` : ''}</p></div><div className="flex gap-3"><button type="button" className="link-button" onClick={() => toggle(webhook)}>{webhook.active ? 'Pausar' : 'Ativar'}</button><button type="button" className="link-button danger-link" onClick={() => remove(webhook.id)}>Excluir</button></div></article>) : <p className="empty-state">Nenhum webhook configurado.</p>}</div></section><section className="panel mt-5"><div className="panel-heading"><div><p className="eyebrow">API</p><h3>Chaves de acesso somente leitura</h3><p className="panel-subtitle">Use X-API-Key para consultar /api/v1/posts, /api/v1/accounts e /api/v1/health.</p></div><button type="button" className="secondary-button" onClick={createKey}>Criar API key</button></div><div className="space-y-2">{apiKeys.length ? apiKeys.map(key => <div className="flex items-center justify-between rounded-lg border border-subtle bg-app p-3 text-sm" key={key.id}><span><strong>{key.name}</strong><small className="ml-2 text-zinc-500">{key.prefix}… · último uso {key.lastUsedAt ? new Date(key.lastUsedAt).toLocaleString('pt-BR') : 'nunca'}</small></span><button type="button" className="link-button danger-link" onClick={() => revokeKey(key.id)}>Revogar</button></div>) : <p className="empty-state">Nenhuma API key criada.</p>}</div></section></section>
}
