import { useEffect, useState } from 'react'
import { apiFetch } from '../lib/api.js'

export function CalendarPage() {
  const now = new Date(); const [month,setMonth] = useState(now.getMonth()+1); const [year,setYear] = useState(now.getFullYear()); const [posts,setPosts] = useState([]); const [editing,setEditing] = useState(null); const [date,setDate] = useState(''); const [message,setMessage] = useState(''); const [error,setError] = useState('')
  const load = () => apiFetch(`/api/posts/calendar?year=${year}&month=${month}`).then(data=>setPosts(data.posts||[])).catch(e=>setError(e.message))
  useEffect(()=>{load()},[year,month])
  function shift(delta){const next=new Date(year,month-1+delta,1);setYear(next.getFullYear());setMonth(next.getMonth()+1);setMessage('')}
  async function remove(post){if(!window.confirm('Excluir esta publicação?'))return;try{await apiFetch(`/api/posts/${post.id}`,{method:'DELETE'});setMessage('Publicação excluída.');load()}catch(e){setError(e.message)}}
  async function reschedule(event){event.preventDefault();try{await apiFetch(`/api/posts/${editing.id}`,{method:'PATCH',body:JSON.stringify({scheduledAt:date})});setEditing(null);setMessage('Publicação reagendada.');load()}catch(e){setError(e.message)}}
  const days=new Date(year,month,0).getDate(); return <section className="page-view"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">PLANEJAMENTO</p><h2>{String(month).padStart(2,'0')}/{year}</h2></div><div><button className="link-button" onClick={()=>shift(-1)}>Anterior</button><button className="link-button" onClick={()=>shift(1)}>Próximo</button></div></div>{message&&<p className="success-message">{message}</p>}{error&&<p className="error-message">{error}</p>}<div className="calendar-grid">{Array.from({length:days},(_,index)=>{const day=index+1;const dayPosts=posts.filter(post=>new Date(post.scheduled_at||post.scheduledAt||post.data_agendamento).getDate()===day);return <div className="calendar-day" key={day}><strong>{day}</strong>{dayPosts.map(post=><div className="calendar-event" key={post.id}><span>{post.text||post.title||'Publicação'}</span><div><button className="link-button" onClick={()=>{setEditing(post);setDate((post.scheduled_at||post.scheduledAt||'').slice(0,16))}}>Editar</button><button className="link-button danger-link" onClick={()=>remove(post)}>Excluir</button></div></div>)}</div>})}</div></section>{editing&&<section className="panel edit-panel"><h2>Reagendar publicação</h2><form className="inline-form" onSubmit={reschedule}><input required type="datetime-local" value={date} onChange={event=>setDate(event.target.value)}/><button className="action-button">Salvar</button><button type="button" className="link-button" onClick={()=>setEditing(null)}>Cancelar</button></form></section>}</section>
}
